excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - vendor/bundle
line_length: 160
identifier_name:
  allowed_symbols: 
    - $
    - _
type_name:
  allowed_symbols:
    - _
nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5
